# Minisys xc7a100tfgg484-1 pin assignments
# Put the variables after the `get_ports` command
set_property -dict {PACKAGE_PIN Y18	 IOSTANDARD LVCMOS33} [get_ports ]; # CLK 晶振的输出，100MHz
set_property -dict {PACKAGE_PIN W4	 IOSTANDARD LVCMOS33} [get_ports ]; # SW0 拨码开关0
set_property -dict {PACKAGE_PIN R4	 IOSTANDARD LVCMOS33} [get_ports ]; # SW1 拨码开关1
set_property -dict {PACKAGE_PIN T4	 IOSTANDARD LVCMOS33} [get_ports ]; # SW2 拨码开关2
set_property -dict {PACKAGE_PIN T5	 IOSTANDARD LVCMOS33} [get_ports ]; # SW3 拨码开关3
set_property -dict {PACKAGE_PIN U5	 IOSTANDARD LVCMOS33} [get_ports ]; # SW4 拨码开关4
set_property -dict {PACKAGE_PIN W6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW5 拨码开关5
set_property -dict {PACKAGE_PIN W5	 IOSTANDARD LVCMOS33} [get_ports ]; # SW6 拨码开关6
set_property -dict {PACKAGE_PIN U6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW7 拨码开关7
set_property -dict {PACKAGE_PIN V5	 IOSTANDARD LVCMOS33} [get_ports ]; # SW8 拨码开关8
set_property -dict {PACKAGE_PIN R6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW9 拨码开关9
set_property -dict {PACKAGE_PIN T6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW10 拨码开关10
set_property -dict {PACKAGE_PIN Y6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW11 拨码开关11
set_property -dict {PACKAGE_PIN AA6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW12 拨码开关12
set_property -dict {PACKAGE_PIN V7	 IOSTANDARD LVCMOS33} [get_ports ]; # SW13 拨码开关13
set_property -dict {PACKAGE_PIN AB7	 IOSTANDARD LVCMOS33} [get_ports ]; # SW14 拨码开关14
set_property -dict {PACKAGE_PIN AB6	 IOSTANDARD LVCMOS33} [get_ports ]; # SW15 拨码开关15
set_property -dict {PACKAGE_PIN V9	 IOSTANDARD LVCMOS33} [get_ports ]; # SW16 拨码开关16
set_property -dict {PACKAGE_PIN V8	 IOSTANDARD LVCMOS33} [get_ports ]; # SW17 拨码开关17
set_property -dict {PACKAGE_PIN AA8	 IOSTANDARD LVCMOS33} [get_ports ]; # SW18 拨码开关18
set_property -dict {PACKAGE_PIN AB8	 IOSTANDARD LVCMOS33} [get_ports ]; # SW19 拨码开关19
set_property -dict {PACKAGE_PIN Y8	 IOSTANDARD LVCMOS33} [get_ports ]; # SW20 拨码开关20
set_property -dict {PACKAGE_PIN Y7	 IOSTANDARD LVCMOS33} [get_ports ]; # SW21 拨码开关21
set_property -dict {PACKAGE_PIN W9	 IOSTANDARD LVCMOS33} [get_ports ]; # SW22 拨码开关22
set_property -dict {PACKAGE_PIN Y9	 IOSTANDARD LVCMOS33} [get_ports ]; # SW23 拨码开关23
set_property -dict {PACKAGE_PIN A21	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD0 LED灯0（绿）
set_property -dict {PACKAGE_PIN E22	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD1 LED灯1（绿）
set_property -dict {PACKAGE_PIN D22	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD2 LED灯2（绿）
set_property -dict {PACKAGE_PIN E21	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD3 LED灯3（绿）
set_property -dict {PACKAGE_PIN D21	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD4 LED灯4（绿）
set_property -dict {PACKAGE_PIN G21	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD5 LED灯5（绿）
set_property -dict {PACKAGE_PIN G22	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD6 LED灯6（绿）
set_property -dict {PACKAGE_PIN F21	 IOSTANDARD LVCMOS33} [get_ports ]; # GLD7 LED灯7（绿）
set_property -dict {PACKAGE_PIN J17	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD0 LED灯8（黄）
set_property -dict {PACKAGE_PIN L14	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD1 LED灯9（黄）
set_property -dict {PACKAGE_PIN L15	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD2 LED灯10（黄）
set_property -dict {PACKAGE_PIN L16	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD3 LED灯11（黄）
set_property -dict {PACKAGE_PIN K16	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD4 LED灯12（黄）
set_property -dict {PACKAGE_PIN M15	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD5 LED灯13（黄）
set_property -dict {PACKAGE_PIN M16	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD6 LED灯14（黄）
set_property -dict {PACKAGE_PIN M17	 IOSTANDARD LVCMOS33} [get_ports ]; # YLD7 LED灯15（黄）
set_property -dict {PACKAGE_PIN N19	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD0 LED灯16（红）
set_property -dict {PACKAGE_PIN N20	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD1 LED灯17（红）
set_property -dict {PACKAGE_PIN M20	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD2 LED灯18（红）
set_property -dict {PACKAGE_PIN K13	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD3 LED灯19（红）
set_property -dict {PACKAGE_PIN K14	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD4 LED灯20-（红）
set_property -dict {PACKAGE_PIN M13	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD5 LED灯21（红）
set_property -dict {PACKAGE_PIN L13	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD6 LED灯22（红）
set_property -dict {PACKAGE_PIN K17	 IOSTANDARD LVCMOS33} [get_ports ]; # RLD7 LED灯23（红）
set_property -dict {PACKAGE_PIN R1	 IOSTANDARD LVCMOS33} [get_ports ]; # S1 按键开关1
set_property -dict {PACKAGE_PIN P1	 IOSTANDARD LVCMOS33} [get_ports ]; # S2 按键开关2
set_property -dict {PACKAGE_PIN P5	 IOSTANDARD LVCMOS33} [get_ports ]; # S3 按键开关3
set_property -dict {PACKAGE_PIN P4	 IOSTANDARD LVCMOS33} [get_ports ]; # S4 按键开关4
set_property -dict {PACKAGE_PIN P2	 IOSTANDARD LVCMOS33} [get_ports ]; # S5 按键开关5
set_property -dict {PACKAGE_PIN C19	 IOSTANDARD LVCMOS33} [get_ports ]; # A0 数码管0使能信号
set_property -dict {PACKAGE_PIN E19	 IOSTANDARD LVCMOS33} [get_ports ]; # A1 数码管1使能信号
set_property -dict {PACKAGE_PIN D19	 IOSTANDARD LVCMOS33} [get_ports ]; # A2 数码管2使能信号
set_property -dict {PACKAGE_PIN F18	 IOSTANDARD LVCMOS33} [get_ports ]; # A3 数码管3使能信号
set_property -dict {PACKAGE_PIN E18	 IOSTANDARD LVCMOS33} [get_ports ]; # A4 数码管4使能信号
set_property -dict {PACKAGE_PIN B20	 IOSTANDARD LVCMOS33} [get_ports ]; # A5 数码管5使能信号
set_property -dict {PACKAGE_PIN A20	 IOSTANDARD LVCMOS33} [get_ports ]; # A6 数码管6使能信号
set_property -dict {PACKAGE_PIN A18	 IOSTANDARD LVCMOS33} [get_ports ]; # A7 数码管7使能信号
set_property -dict {PACKAGE_PIN F15	 IOSTANDARD LVCMOS33} [get_ports ]; # CA 数码管A段
set_property -dict {PACKAGE_PIN F13	 IOSTANDARD LVCMOS33} [get_ports ]; # CB 数码管B段
set_property -dict {PACKAGE_PIN F14	 IOSTANDARD LVCMOS33} [get_ports ]; # CC 数码管C段
set_property -dict {PACKAGE_PIN F16	 IOSTANDARD LVCMOS33} [get_ports ]; # CD 数码管D段
set_property -dict {PACKAGE_PIN E17	 IOSTANDARD LVCMOS33} [get_ports ]; # CE 数码管E段
set_property -dict {PACKAGE_PIN C14	 IOSTANDARD LVCMOS33} [get_ports ]; # CF 数码管F段
set_property -dict {PACKAGE_PIN C15	 IOSTANDARD LVCMOS33} [get_ports ]; # CG 数码管G段
set_property -dict {PACKAGE_PIN E13	 IOSTANDARD LVCMOS33} [get_ports ]; # DP 数码管DP段
set_property -dict { PACKAGE_PIN Y19 IOSTANDARD LVCMOS33 } [get_ports  uart_rx]; # UART接收端  
set_property -dict { PACKAGE_PIN V18 IOSTANDARD LVCMOS33 } [get_ports  uart_tx]; # UART发送端